### ISSUE TITLE
Escape e virgolette

### ISSUE THREAD

**Issue by nemobis** [synapta/wikidata-mibact-luoghi-cultura#12]
In https://www.wikidata.org/wiki/Q54087852 vedo un'etichetta: `Porta delle mura del Borgo detta "Porta di Borgo vecchio o di Santa Maria\"`.

**Comment by alemela** [comment]
Fatto in: https://github.com/synapta/wikidata-mibact-luoghi-cultura/commit/29102ebdba420370f2813245dd278f58913e19dd
