### ISSUE TITLE
Aggiunta di P31 dove richiesto dai vincoli

### ISSUE THREAD

**Issue by nemobis** [synapta/wikidata-mibact-luoghi-cultura#13]
Già [richiesto](https://www.wikidata.org/?diff=692970690) ma documento per chiarezza: in casi come [Q54874778](https://www.wikidata.org/wiki/Q54874778), P131 e P1435 danno una violazione dei vincoli perché mancano P31.

Dovrebbe bastare qualcosa di generico come Q684740 o alla peggio Q4406616.

**Comment by alemela** [comment]
Per quelli che nei dati non c'è nulla e non sono in una categoria facile da individuare metto come fallback Q684740, così tutti hanno un P31

**Comment by alemela** [comment]
Fatto in: https://github.com/synapta/wikidata-mibact-luoghi-cultura/commit/0d6660ec4c4e346bb768faba8e70fd52b26c6b0d
