### ISSUE TITLE
Matching con enti controllanti tramite url o email

### ISSUE THREAD

**Issue by alemela** [synapta/wikidata-mibact-luoghi-cultura#7]
Segue query per fare equivalenza tra domini:
```
SELECT ?oth
WHERE {
  wd:Q53016463 wdt:P856 ?website .
  BIND( 
    IF(
      CONTAINS((strafter(str(?website), "://" )), "/"), 
      STRBEFORE((strafter(str(?website), "://" )), "/"), 
      strafter(str(?website), "://" )
    )
  as ?domain)
  BIND(REPLACE(?domain, "([^\\.]+\\.|)([^\\.]+\\..*)", "$2") as ?secondLevelDomain)
  
  ?oth wdt:P856 ?websiteOth .
  BIND( 
    IF(
      CONTAINS((strafter(str(?websiteOth), "://" )), "/"), 
      STRBEFORE((strafter(str(?websiteOth), "://" )), "/"), 
      strafter(str(?websiteOth), "://" )
    )
  as ?domainOth)
  BIND(REPLACE(?domainOth, "([^\\.]+\\.|)([^\\.]+\\..*)", "$2") as ?secondLevelDomainOth)
  
  FILTER (?secondLevelDomain = ?secondLevelDomainOth)
       
  FILTER (?oth != wd:Q53016463) #not my searched one
}
```

**Comment by nemobis** [comment]
Sarebbe utile aggiungere anche la PEC. Dovrebbero essere tutte in questi CSV:
http://www.indicepa.gov.it/documentale/n-opendata.php

**Comment by alemela** [comment]
@nemobis a livello ontologico non sono sicuro che su WIkidata si stia facendo un buon lavoro per i comuni. Hanno mischiato il luogo con l'amministrazione IMHO.

Detto questo sì, tutti i dati IPA & Co sarebbe bello che a tendere finiscano su Wikidata (anche se non è banale tenerli in sync "gratis" perché vengono continuamente aggiornati e occorre stargli dietro).

Tuttavia per questa issue temo che questa desiderata debba rimanere tale

**Comment by nemobis** [comment]
Alessio Melandri, 13/07/2018 11:52:
> Tuttavia per questa issue temo che questa desiderata debba rimanere tale

Concordo, non importerei la PEC in Wikidata. Se capita però di scrivere 
un'interrogazione o programmino che estragga i dati associandoli a 
indirizzi di posta elettronica, sospetto che arricchire i dati in uscita 
colle PEC da quei CSV sia fattibile.
